name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * 0 # weekly
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }} # need ssh
        run: julia -e 'using CompatHelper; CompatHelper.main()'

# based on:
# https://github.com/JuliaRegistries/CompatHelper.jl
